apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstackapp
  template:
    metadata:
      labels:
        app: fullstackapp
    spec:
      containers:   
        - name: fullstackapp
          image: elijahgolnik/fullstackapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80