apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstackapp
  template:
    metadata:
      labels:
        app: fullstackapp
    spec:
      containers:   
        - name: fullstackapp
          image: elijahgolnik/fullstackapp:latest
          image: elijahgolnik/fullstackapp/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 62566