name: Docker Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} ./fullstackapp

      - name: Build and tag Docker Image
        run: docker build -t myapp:${{ github.sha }}  -t myapp${{ github.ref }} ./fullstackapp

      - name: Push Docker Image to Docker Hub
        run: docker push myapp:${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build multi-arch Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t myapp:${{ github.sha }} .

      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image myapp:${{ github.sha }}
          if [ $? -ne 0 ]; then exit 1; fi
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      
          
  