name: Build and Deploy to Local Kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

        # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker Image
        run: docker build -t myapp:${{ github.sha }}  -t myapp:latest ./fullstackapp

      - name: Push Docker Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./fullstackapp
          push: true
          tags: elijahgolnik/myapp:${{ github.sha }},elijahgolnik/myapp:latest
          platforms: linux/amd64,linux/arm64

      # 5. Ensure kubeconfig is available
      - name: Set kubeconfig
        run: |
          mkdir -p $HOME/.kube
          cp ~/.kube/config $HOME/.kube/config

      # 6. Verify cluster connection (good for debugging)
      - name: Verify Kubernetes connection
        run: |
          kubectl config current-context
          kubectl get nodes

      # 7. Deploy manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f fullstackapp/k8s/

      # 8. Force rollout (important when using :latest)
      - name: Restart deployment
        run: |
          kubectl rollout restart deployment fullstackapp

      # 9. Show status (debug visibility)
      - name: Show deployment status
        run: |
          kubectl get pods
          kubectl get svc